### PR TITLE
test

### PR DESCRIPTION
**Pull request by doudz**

### CODE REVIEW

**Comment by pdecat** [comment]
Hi @doudz, I'm going to submit my changes in separate PRs.

**Comment by pdecat** [comment]
ok, https://github.com/pdecat/homeassistant-zigate/tree/add_dependencies is already superseeded by https://github.com/doudz/homeassistant-zigate/commit/68e25fe347e96123f2abb756b82493fea140f638

**Comment by pdecat** [comment]
same for https://github.com/pdecat/homeassistant-zigate/tree/use_ieee_for_entity_ids by https://github.com/doudz/homeassistant-zigate/commit/17129811728ba2dd6764b9492d5688ab6b94cc1c

**Comment by pdecat** [comment]
ok, nothing left to contribute.

**Comment by pdecat** [comment]
note: sorry I did not contribute those changes earlier but if I remember correctly, this repo was archived back then.

**Comment by pdecat** [comment]
FYI, I've managed to switch from my fork back to your master.
So far so good, everything's working as before.

**Comment by doudz** [comment]
good to know, many thanks for what you've done

**Pull request closed without merging**
